Repository LOTTE-5IVE/kka-kka, pull requests merged in 2022-09, with the labels that each got.

#11 chore: 프론트엔드 프로젝트 기초환경 세팅
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/README.md
  frontend/components/NavBar.js
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.js
  frontend/pages/api/hello.js
  frontend/pages/index.js
  frontend/pages/join.js
  frontend/pages/login.js
  frontend/pages/productList.js
  frontend/public/favicon.ico
  frontend/public/vercel.svg
  frontend/styles/Home.module.css
  frontend/styles/globals.css
Labels: 🌠 FE, ⚙️ 설정

#13 feat: 메인 서비스 비동기 로깅 설정
  .github/PULL_REQUEST_TEMPLATE.md
  backend/main-service/build.gradle
  backend/main-service/src/main/resources/application.yml
  backend/main-service/src/main/resources/bootstrap.yml
  backend/main-service/src/main/resources/logback-spring.xml
Labels: 🍃 BE, ⚙️ 설정

#15 chore: 프론트 헤더,푸터, 네브바 추가
  frontend/.babelrc.json
  frontend/components/common/FooterComp.js
  frontend/components/common/HeaderComp.js
  frontend/components/common/Layout.js
  frontend/components/common/NavBar.js
  frontend/components/common/Title.js
  frontend/components/main/C-Recomm.js
  frontend/components/main/R-Recomm.js
  frontend/components/main/Slider.js
  frontend/components/member/SNSButton.js
  frontend/components/product/Productlist.js
  frontend/components/product/Sidebar.js
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.js
  frontend/pages/index.js
  frontend/pages/member/cart.js
  frontend/pages/member/join.js
  frontend/pages/member/login.js
  frontend/pages/member/mypage.js
  frontend/pages/payment/payment.js
  frontend/pages/product/productDetail.js
  frontend/pages/product/productList.js
  frontend/pages/product/productSearch.js
  frontend/public/1.png
  frontend/public/2.png
  frontend/public/common/main_search.png
  frontend/public/common/top_cart.png
  frontend/public/common/top_mypage.png
  frontend/styles/Home.module.css
  frontend/styles/Home.module.scss
  frontend/styles/globals.css
Labels: 🌠 FE, ⚙️ 설정

#17 feat: 카테고리 상품 목록 조회 , 상세 보기 기능 구현
  backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
  backend/main-service/src/main/java/kkakka/mainservice/cart/domain/Cart.java
  backend/main-service/src/main/java/kkakka/mainservice/cart/domain/CartItem.java
  backend/main-service/src/main/java/kkakka/mainservice/cart/domain/repository/CartItemRepository.java
  backend/main-service/src/main/java/kkakka/mainservice/cart/domain/repository/CartRepository.java
  backend/main-service/src/main/java/kkakka/mainservice/cart/ui/CartController.java
  backend/main-service/src/main/java/kkakka/mainservice/cart/ui/dto/CartRequestDto.java
  backend/main-service/src/main/java/kkakka/mainservice/category/application/CategoryService.java
  backend/main-service/src/main/java/kkakka/mainservice/category/domain/Category.java
  backend/main-service/src/main/java/kkakka/mainservice/category/domain/repository/CategoryRepository.java
  backend/main-service/src/main/java/kkakka/mainservice/category/ui/CategoryController.java
  backend/main-service/src/main/java/kkakka/mainservice/category/ui/dto/ResponseCategoryProducts.java
  backend/main-service/src/main/java/kkakka/mainservice/common/config/MapperConfig.java
  backend/main-service/src/main/java/kkakka/mainservice/common/config/WebConfig.java
  backend/main-service/src/main/java/kkakka/mainservice/member/domain/Member.java
  backend/main-service/src/main/java/kkakka/mainservice/member/domain/repository/MemberRepository.java
  backend/main-service/src/main/java/kkakka/mainservice/member/ui/MemberController.java
  backend/main-service/src/main/java/kkakka/mainservice/product/application/ProductService.java
  backend/main-service/src/main/java/kkakka/mainservice/product/domain/Product.java
  backend/main-service/src/main/java/kkakka/mainservice/product/domain/repository/ProductRepository.java
  backend/main-service/src/main/java/kkakka/mainservice/product/ui/ProductController.java
  backend/main-service/src/main/java/kkakka/mainservice/product/ui/dto/ProductResponseDto.java
Labels: 🚀 기능, 🍃 BE

#19 feat: 메인화면(맞춤,리뷰추천),로그인&회원가입,장바구니
  frontend/components/common/ButtonComp.js
  frontend/components/common/HeaderComp.js
  frontend/components/common/Layout.js
  frontend/components/main/C-Recomm.js
  frontend/components/main/C_Recomm.js
  frontend/components/main/R-Recomm.js
  frontend/components/main/R_Recomm.js
  frontend/components/main/Slider.js
  frontend/components/member/SNSButton.js
  frontend/components/product/ProductEc.js
  frontend/components/product/ProductRec.js
  frontend/pages/index.js
  frontend/pages/member/cart.js
  frontend/pages/member/join.js
  frontend/pages/member/login.js
  frontend/pages/member/mypage.js
  frontend/public/main/1.png
  frontend/public/main/2.png
  frontend/public/member/apple.png
  frontend/public/member/kakao.png
  frontend/public/member/naver.png
  frontend/public/sample.png
Labels: 🚀 기능, 🌠 FE

#34 feat: 상품목록 프론트엔드 페이지 구현
  frontend/components/common/HeaderComp.js
  frontend/components/common/NavBar.js
  frontend/components/main/C_Recomm.js
  frontend/components/main/R_Recomm.js
  frontend/components/product/ProductEc.js
  frontend/components/product/ProductRec.js
  frontend/components/product/Sidebar.js
  frontend/db.json
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.js
  frontend/pages/index.js
  frontend/pages/product/index.js
Labels: 🚀 기능, 🌠 FE

#36 feat: 마이페이지 프론트엔드 페이지 구현
  frontend/components/mypage/MyInfoCard.js
  frontend/components/mypage/Mysidebar.js
  frontend/pages/member/cart.js
  frontend/pages/mypage/myCoupon.js
  frontend/pages/mypage/myEdit.js
  frontend/pages/mypage/myOrder.js
  frontend/pages/product/[cat_id].js
  frontend/pages/product/productDetail/[id].js
Labels: 🚀 기능, 🌠 FE

#38 refactor: 인증 서비스 분리
  backend/main-service/src/main/java/kkakka/mainservice/auth/application/AuthService.java
  backend/main-service/src/main/java/kkakka/mainservice/auth/application/UserProfile.java
  backend/main-service/src/main/java/kkakka/mainservice/auth/application/dto/SocialProviderCodeDto.java
  backend/main-service/src/main/java/kkakka/mainservice/auth/application/dto/UserProfileDto.java
  backend/main-service/src/main/java/kkakka/mainservice/auth/domain/Provider.java
  backend/main-service/src/main/java/kkakka/mainservice/auth/infrastructure/kakao/KakaoUserProfile.java
  backend/main-service/src/main/java/kkakka/mainservice/auth/infrastructure/naver/NaverUserProfile.java
  backend/main-service/src/main/java/kkakka/mainservice/auth/ui/AuthController.java
  backend/main-service/src/main/java/kkakka/mainservice/common/config/WebMvcConfig.java
  backend/main-service/src/main/java/kkakka/mainservice/member/auth/application/MemberAuthService.java
  backend/main-service/src/main/java/kkakka/mainservice/member/auth/application/dto/SocialProviderCodeDto.java
  backend/main-service/src/main/java/kkakka/mainservice/member/auth/application/dto/UserProfile.java
  backend/main-service/src/main/java/kkakka/mainservice/member/auth/infrastructure/ResponseConverter.java
  backend/main-service/src/main/java/kkakka/mainservice/member/auth/ui/LoginMember.java
  backend/main-service/src/main/java/kkakka/mainservice/member/auth/ui/MemberAuthController.java
  backend/main-service/src/main/java/kkakka/mainservice/member/auth/ui/dto/SocialProviderCodeRequest.java
  backend/main-service/src/main/java/kkakka/mainservice/member/auth/ui/dto/TokenDto.java
  backend/main-service/src/main/java/kkakka/mainservice/member/member/application/MemberService.java
  backend/main-service/src/main/java/kkakka/mainservice/member/member/domain/Member.java
  backend/main-service/src/main/java/kkakka/mainservice/member/member/domain/MemberProviderName.java
  backend/main-service/src/main/java/kkakka/mainservice/member/member/domain/Provider.java
  backend/main-service/src/main/resources/bootstrap.yml
  backend/main-service/src/test/java/kkakka/mainservice/fixture/TestUserProfile.java
  backend/main-service/src/test/java/kkakka/mainservice/member/acceptance/LoginAcceptanceTest.java
  backend/main-service/src/test/java/kkakka/mainservice/member/application/MemberServiceTest.java
  frontend/pages/oauth.js
Labels: 🛠 리팩토링, 🚀 기능, 🍃 BE

#33 feat: RestDocs를 사용한 API 문서화 구현
  backend/main-service/build.gradle
  backend/main-service/gradlew
  backend/main-service/src/docs/asciidoc/index.adoc
  backend/main-service/src/test/java/kkakka/mainservice/DocumentConfiguration.java
  backend/main-service/src/test/java/kkakka/mainservice/member/acceptance/LoginAcceptanceTest.java
Labels: 📋 문서, 🚀 기능, 🍃 BE, ⚙️ 설정

#40 fix: 패키지 변경으로 인한 import 문제 해결
  backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
Labels: 🍃 BE, 🚨 핫픽스
