Repository LOTTE-5IVE/kka-kka, pull requests merged in 2022-10, with the labels that each got.

#44 fix: interceptor 가 제대로 동작하지 않는 문제
  backend/main-service/src/main/java/kkakka/mainservice/common/config/WebMvcConfig.java
  backend/main-service/src/main/java/kkakka/mainservice/member/member/ui/MemberController.java
  backend/main-service/src/test/java/kkakka/mainservice/fixture/TestMember.java
  backend/main-service/src/test/java/kkakka/mainservice/member/AuthorityAcceptanceTest.java
  backend/main-service/src/test/java/kkakka/mainservice/member/acceptance/MemberAcceptanceTest.java
Labels: 🍃 BE, 🚨 핫픽스

#42 fix: 소셜로그인 500 에러 해결
  backend/main-service/src/main/java/kkakka/mainservice/common/config/WebMvcConfig.java
  backend/main-service/src/main/java/kkakka/mainservice/member/auth/ui/dto/SocialProviderCodeRequest.java
  backend/main-service/src/main/java/kkakka/mainservice/member/member/ui/MemberController.java
  backend/main-service/src/test/java/kkakka/mainservice/fixture/TestMember.java
  backend/main-service/src/test/java/kkakka/mainservice/member/AuthorityAcceptanceTest.java
  backend/main-service/src/test/java/kkakka/mainservice/member/acceptance/MemberAcceptanceTest.java
Labels: 🍃 BE, 🚨 핫픽스

#55 fix: 손실파일복구
  frontend/components/admin/AdminSidebar.js
  frontend/components/common/ButtonComp.js
  frontend/components/common/HeaderComp.js
  frontend/components/common/NavBar.js
  frontend/components/main/R_Recomm.js
  frontend/components/mypage/MyCoupon.js
  frontend/components/mypage/MyCouponCard.js
  frontend/components/mypage/MyInfoCard.js
  frontend/components/mypage/MyOrder.js
  frontend/components/mypage/Mysidebar.js
  frontend/components/payment/DaumPost.js
  frontend/components/product/Info.js
  frontend/components/product/Nutri.js
  frontend/components/product/ProductEc.js
  frontend/components/product/ProductRec.js
  frontend/components/product/Review.js
  frontend/components/product/Sidebar.js
  frontend/db.json
  frontend/etcComp/NavBar.js
  frontend/etcComp/myCoupon.js
  frontend/etcComp/myEdit.js
  frontend/etcComp/myOrder.js
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.js
  frontend/pages/admin/index.js
  frontend/pages/join.js
  frontend/pages/member/cart.js
  frontend/pages/mypage/index.js
  frontend/pages/payment/index.js
  frontend/pages/product/index.js
  frontend/pages/product/productDetail/[id].js
  frontend/public/mg.png
Labels: 🌠 FE, ❗️ 이슈

#46 refactor: 장바구니 멤버 검증 로직 추가 및 리팩토링
  backend/main-service/build.gradle
  backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
  backend/main-service/src/main/java/kkakka/mainservice/cart/domain/repository/CartItemRepository.java
  backend/main-service/src/main/java/kkakka/mainservice/cart/ui/CartController.java
  backend/main-service/src/main/java/kkakka/mainservice/common/config/WebMvcConfig.java
  backend/main-service/src/main/java/kkakka/mainservice/member/auth/ui/dto/SocialProviderCodeRequest.java
  backend/main-service/src/main/resources/bootstrap.yml
  backend/main-service/src/test/java/kkakka/mainservice/cart/TestDataLoader.java
  backend/main-service/src/test/java/kkakka/mainservice/cart/ui/CartAcceptanceTest.java
  backend/main-service/src/test/java/kkakka/mainservice/product/acceptance/ProductAcceptanceTest.java
Labels: 🛠 리팩토링, 🍃 BE

#45 feat: 최신순으로 주문내역 조회
  backend/main-service/src/main/java/kkakka/mainservice/order/application/OrderService.java
  backend/main-service/src/main/java/kkakka/mainservice/order/domain/Order.java
  backend/main-service/src/main/java/kkakka/mainservice/order/domain/repository/OrderRepository.java
  backend/main-service/src/main/java/kkakka/mainservice/order/ui/OrderController.java
  backend/main-service/src/main/java/kkakka/mainservice/order/ui/dto/OrderRequest.java
  backend/main-service/src/main/java/kkakka/mainservice/order/ui/dto/OrderResponse.java
  backend/main-service/src/main/java/kkakka/mainservice/order/ui/dto/ProductOrderResponse.java
  backend/main-service/src/main/java/kkakka/mainservice/order/ui/dto/ProductResponse.java
  backend/main-service/src/main/java/kkakka/mainservice/product/domain/Product.java
  backend/main-service/src/test/java/kkakka/mainservice/order/application/OrderServiceTest.java
Labels: 🚀 기능, 🍃 BE

#31 feat: 상품 주문 구현
  backend/main-service/build.gradle
  backend/main-service/src/main/java/kkakka/mainservice/category/ui/dto/ResponseCategoryProducts.java
  backend/main-service/src/main/java/kkakka/mainservice/common/LocalDateTimeSerializer.java
  backend/main-service/src/main/java/kkakka/mainservice/order/application/OrderService.java
  backend/main-service/src/main/java/kkakka/mainservice/order/application/dto/OrderDto.java
  backend/main-service/src/main/java/kkakka/mainservice/order/application/dto/ProductOrderDto.java
  backend/main-service/src/main/java/kkakka/mainservice/order/domain/Order.java
  backend/main-service/src/main/java/kkakka/mainservice/order/domain/ProductOrder.java
  backend/main-service/src/main/java/kkakka/mainservice/order/domain/repository/OrderRepository.java
  backend/main-service/src/main/java/kkakka/mainservice/order/domain/repository/ProductOrderRepository.java
  backend/main-service/src/main/java/kkakka/mainservice/order/ui/OrderController.java
  backend/main-service/src/main/java/kkakka/mainservice/order/ui/dto/OrderRequest.java
  backend/main-service/src/main/java/kkakka/mainservice/order/ui/dto/OrderResponse.java
  backend/main-service/src/main/java/kkakka/mainservice/order/ui/dto/ProductOrderResponse.java
  backend/main-service/src/main/java/kkakka/mainservice/order/ui/dto/ProductResponse.java
  backend/main-service/src/main/java/kkakka/mainservice/product/domain/Product.java
  backend/main-service/src/main/java/kkakka/mainservice/product/ui/ProductController.java
  backend/main-service/src/test/java/kkakka/mainservice/order/acceptance/OrderAcceptanceTest.java
  backend/main-service/src/test/java/kkakka/mainservice/order/application/OrderServiceTest.java
Labels: 🚀 기능, 🍃 BE

#60 feat: 회원 인증 공통 로직 분리
  backend/main-service/src/docs/asciidoc/index.adoc
  backend/main-service/src/main/java/kkakka/mainservice/member/auth/ui/MemberOnly.java
  backend/main-service/src/main/java/kkakka/mainservice/member/auth/util/LoginAop.java
  backend/main-service/src/main/java/kkakka/mainservice/member/member/application/MemberService.java
  backend/main-service/src/main/java/kkakka/mainservice/member/member/domain/Member.java
  backend/main-service/src/main/java/kkakka/mainservice/member/member/ui/MemberController.java
  backend/main-service/src/main/java/kkakka/mainservice/member/member/ui/dto/MemberResponse.java
  backend/main-service/src/test/java/kkakka/mainservice/member/acceptance/MemberAcceptanceTest.java
Labels: 🛠 리팩토링, 🚀 기능, 🍃 BE

#58 feat: 회원 정보 조회 기능 구현
  backend/main-service/src/docs/asciidoc/index.adoc
  backend/main-service/src/main/java/kkakka/mainservice/member/auth/infrastructure/LoginInterceptor.java
  backend/main-service/src/main/java/kkakka/mainservice/member/member/application/MemberService.java
  backend/main-service/src/main/java/kkakka/mainservice/member/member/domain/Member.java
  backend/main-service/src/main/java/kkakka/mainservice/member/member/ui/MemberController.java
  backend/main-service/src/main/java/kkakka/mainservice/member/member/ui/dto/MemberResponse.java
  backend/main-service/src/test/java/kkakka/mainservice/member/acceptance/MemberAcceptanceTest.java
Labels: 🚀 기능, 🍃 BE

#61 feat: 상품 기초 데이터 추가
  backend/main-service/build.gradle
  backend/main-service/src/main/java/kkakka/mainservice/DataLoadRunner.java
  backend/main-service/src/main/java/kkakka/mainservice/DataLoader.java
  backend/main-service/src/main/java/kkakka/mainservice/cart/domain/CartItem.java
  backend/main-service/src/main/java/kkakka/mainservice/category/ui/CategoryController.java
  backend/main-service/src/main/java/kkakka/mainservice/member/member/ui/MemberController.java
  backend/main-service/src/main/java/kkakka/mainservice/product/domain/Product.java
  backend/main-service/src/main/java/kkakka/mainservice/product/ui/ProductController.java
  backend/main-service/src/test/java/kkakka/mainservice/order/application/OrderServiceTest.java
Labels: 🚀 기능, 🍃 BE

#73 feat: flyway 적용
  backend/main-service/build.gradle
  backend/main-service/src/main/java/kkakka/mainservice/cart/domain/CartItem.java
  backend/main-service/src/main/resources/db/migration/local/V2210061229__init.sql
  backend/main-service/src/main/resources/db/migration/local/V2210111459__create_order.sql
  backend/main-service/src/main/resources/db/migration/local/V2210111504__create_product_order.sql
  backend/main-service/src/test/java/kkakka/mainservice/TestContext.java
  backend/main-service/src/test/java/kkakka/mainservice/member/application/MemberServiceTest.java
  backend/main-service/src/test/java/kkakka/mainservice/member/domain/MemberRepositoryTest.java
  backend/main-service/src/test/java/kkakka/mainservice/order/application/OrderServiceTest.java
Labels: 🚀 기능, 🍃 BE

#79 chore: 백엔드 도커파일 생성
  backend/apigateway-service/Dockerfile
  backend/config-service/Dockerfile
  backend/discovery-service/Dockerfile
  backend/main-service/Dockerfile
  backend/main-service/src/main/resources/static/index.html
Labels: 👷 인프라, 🍃 BE

#74 feat: 구글 로그인 API 적용
  backend/main-service/build.gradle
  backend/main-service/src/main/java/kkakka/mainservice/auth/domain/ProviderName.java
  backend/main-service/src/main/java/kkakka/mainservice/auth/infrastructure/SocialClientFactory.java
  backend/main-service/src/main/java/kkakka/mainservice/auth/infrastructure/google/GoogleClient.java
  backend/main-service/src/main/java/kkakka/mainservice/auth/infrastructure/google/GoogleOauthInfo.java
  backend/main-service/src/main/java/kkakka/mainservice/auth/infrastructure/google/GoogleUserProfile.java
  backend/main-service/src/main/java/kkakka/mainservice/auth/infrastructure/google/dto/GoogleTokenRequest.java
  backend/main-service/src/main/java/kkakka/mainservice/auth/infrastructure/google/util/BirthConverter.java
  backend/main-service/src/main/java/kkakka/mainservice/member/member/domain/MemberProviderName.java
  frontend/components/GoogleLogin.js
  frontend/pages/join.js
  frontend/pages/oauth.js
Labels: 🚀 기능, 🍃 BE

#77 feat: 카테고리, 상품명 통합 검색 기능 구현
  backend/main-service/src/docs/asciidoc/index.adoc
  backend/main-service/src/main/java/kkakka/mainservice/order/application/dto/ProductOrderDto.java
  backend/main-service/src/main/java/kkakka/mainservice/product/SearchDto.java
  backend/main-service/src/main/java/kkakka/mainservice/product/application/ProductService.java
  backend/main-service/src/main/java/kkakka/mainservice/product/domain/Product.java
  backend/main-service/src/main/java/kkakka/mainservice/product/domain/SearchWords.java
  backend/main-service/src/main/java/kkakka/mainservice/product/domain/repository/ProductRepository.java
  backend/main-service/src/main/java/kkakka/mainservice/product/ui/ProductController.java
  backend/main-service/src/main/java/kkakka/mainservice/product/ui/dto/ProductResponseDto.java
  backend/main-service/src/main/java/kkakka/mainservice/product/ui/dto/SearchRequest.java
  backend/main-service/src/main/resources/static/index.html
  backend/main-service/src/test/java/kkakka/mainservice/product/acceptance/ProductAcceptanceTest.java
  backend/main-service/src/test/java/kkakka/mainservice/product/application/ProductServiceTest.java
Labels: 🚀 기능, 🍃 BE

#95 Refactor: 레이아웃 분리
  frontend/layouts/EnrollLayout.js
  frontend/layouts/LoginCheckLayout.js
  frontend/layouts/MyPageLayout.js
  frontend/layouts/ProductDetailLayout.js
  frontend/layouts/ProductLayout.js
Labels: 🛠 리팩토링, 🌠 FE

#96 Refactor: 디렉터리 구조 변경
  frontend/README.md
  frontend/apis/Apis.js
  frontend/components/admin/ApplyCategory.js
  frontend/components/admin/ApplyProduct.js
  frontend/components/admin/ProductEnroll.js
  frontend/components/admin/ProductSearch.js
  frontend/components/admin/PromotionEnroll.js
  frontend/components/admin/PromotionSearch.js
  frontend/components/common/Button/AdminButton.js
  frontend/components/common/Button/Button.js
  frontend/components/common/Button/ButtonComp.js
  frontend/components/common/HeaderComp.js
  frontend/components/common/NavBar.js
  frontend/components/coupon/CouponDown.js
  frontend/components/coupon/CouponModal.js
  frontend/components/etc/NavBar.js
  frontend/components/etc/[cat_id].js
  frontend/components/etc/[id].js
  frontend/components/etc/join.js
  frontend/components/etc/myCoupon.js
  frontend/components/etc/myEdit.js
  frontend/components/etc/myOrder.js
  frontend/components/etc/productDetail.js
  frontend/components/main/R_Recomm.js
  frontend/components/mypage/MyCoupon.js
  frontend/components/mypage/MyInfoCard.js
  frontend/components/mypage/MyOrder.js
  frontend/components/payment/PayInfo.js
  frontend/components/product/ProductInfo.js
  frontend/components/product/ProductRec.js
  frontend/components/product/ProductRecCard.js
  frontend/components/product/Sidebar.js
  frontend/etcComp/myCoupon.js
  frontend/etcComp/myOrder.js
  frontend/hooks/useMemberInfo.js
  frontend/layouts/EnrollLayout.js
  frontend/layouts/LoginCheckLayout.js
  frontend/layouts/MyPageLayout.js
  frontend/layouts/ProductDetailLayout.js
  frontend/layouts/ProductLayout.js
  frontend/next.config.js
  frontend/pages/admin/index.js
  frontend/pages/member/cart.js
  frontend/pages/member/join.js
  frontend/pages/member/login.js
  frontend/pages/member/mypage.js
  frontend/pages/mypage/index.js
  frontend/pages/mypage/myEdit.js
  frontend/pages/oauth.js
  frontend/pages/payment/index.js
  frontend/pages/product/index.js
  frontend/pages/product/productDetail/index.js
  frontend/public/common/cancel.png
  frontend/public/common/cancelred.png
  frontend/public/member/google.png
  frontend/styles/Home.module.css
Labels: 🛠 리팩토링, 🌠 FE

#101 feat: 할인 등록, 삭제, 조회 기능 추가
  backend/main-service/src/docs/asciidoc/index.adoc
  backend/main-service/src/main/java/kkakka/mainservice/category/domain/repository/CategoryRepository.java
  backend/main-service/src/main/java/kkakka/mainservice/common/exception/InvalidCouponRequestException.java
  backend/main-service/src/main/java/kkakka/mainservice/coupon/application/DiscountService.java
  backend/main-service/src/main/java/kkakka/mainservice/coupon/domain/Discount.java
  backend/main-service/src/main/java/kkakka/mainservice/coupon/domain/DiscountType.java
  backend/main-service/src/main/java/kkakka/mainservice/coupon/domain/repository/DiscountRepository.java
  backend/main-service/src/main/java/kkakka/mainservice/coupon/ui/CouponController.java
  backend/main-service/src/main/java/kkakka/mainservice/coupon/ui/dto/DiscountRequestDto.java
  backend/main-service/src/main/java/kkakka/mainservice/coupon/ui/dto/DiscountResponseDto.java
  backend/main-service/src/main/java/kkakka/mainservice/product/domain/Product.java
  backend/main-service/src/test/java/kkakka/mainservice/coupon/acceptance/DiscountAcceptanceTest.java
  backend/main-service/src/test/java/kkakka/mainservice/coupon/application/DiscountServiceTest.java
Labels: 🚀 기능, 🍃 BE

#67 feat: 쿠폰 CRUD 기능 구현
  backend/main-service/src/docs/asciidoc/index.adoc
  backend/main-service/src/main/java/kkakka/mainservice/category/domain/repository/CategoryRepository.java
  backend/main-service/src/main/java/kkakka/mainservice/common/LocalDateTimeDeserializer.java
  backend/main-service/src/main/java/kkakka/mainservice/common/LocalDateTimeSerializer.java
  backend/main-service/src/main/java/kkakka/mainservice/common/config/WebMvcConfig.java
  backend/main-service/src/main/java/kkakka/mainservice/common/exception/InvalidCouponRequestException.java
  backend/main-service/src/main/java/kkakka/mainservice/coupon/application/CouponService.java
  backend/main-service/src/main/java/kkakka/mainservice/coupon/application/DiscountService.java
  backend/main-service/src/main/java/kkakka/mainservice/coupon/domain/Coupon.java
  backend/main-service/src/main/java/kkakka/mainservice/coupon/domain/Discount.java
  backend/main-service/src/main/java/kkakka/mainservice/coupon/domain/DiscountType.java
  backend/main-service/src/main/java/kkakka/mainservice/coupon/domain/MemberCoupon.java
  backend/main-service/src/main/java/kkakka/mainservice/coupon/domain/PriceRule.java
  backend/main-service/src/main/java/kkakka/mainservice/coupon/domain/repository/CouponRepository.java
  backend/main-service/src/main/java/kkakka/mainservice/coupon/domain/repository/DiscountRepository.java
  backend/main-service/src/main/java/kkakka/mainservice/coupon/domain/repository/MemberCouponRepository.java
  backend/main-service/src/main/java/kkakka/mainservice/coupon/ui/CouponController.java
  backend/main-service/src/main/java/kkakka/mainservice/coupon/ui/dto/CouponRequestDto.java
  backend/main-service/src/main/java/kkakka/mainservice/coupon/ui/dto/CouponResponseDto.java
  backend/main-service/src/main/java/kkakka/mainservice/coupon/ui/dto/DiscountRequestDto.java
  backend/main-service/src/main/java/kkakka/mainservice/coupon/ui/dto/DiscountResponseDto.java
  backend/main-service/src/main/java/kkakka/mainservice/member/member/application/MemberService.java
  backend/main-service/src/main/java/kkakka/mainservice/member/member/domain/Member.java
  backend/main-service/src/main/java/kkakka/mainservice/member/member/domain/Provider.java
  backend/main-service/src/main/java/kkakka/mainservice/member/member/domain/repository/MemberRepository.java
  backend/main-service/src/main/java/kkakka/mainservice/product/domain/Product.java
  backend/main-service/src/main/java/kkakka/mainservice/product/domain/repository/ProductRepository.java
  backend/main-service/src/main/resources/db/migration/local/V2210132017__create_coupon.sql
  backend/main-service/src/main/resources/db/migration/local/V2210132018__create_memercoupon.sql
  backend/main-service/src/test/java/kkakka/mainservice/coupon/acceptance/CouponAcceptanceTest.java
  backend/main-service/src/test/java/kkakka/mainservice/coupon/acceptance/DiscountAcceptanceTest.java
  backend/main-service/src/test/java/kkakka/mainservice/coupon/application/CouponServiceTest.java
  backend/main-service/src/test/java/kkakka/mainservice/coupon/application/DiscountServiceTest.java
Labels: 🚀 기능, 🍃 BE

#89 fix: jar 환경의 구동에서 resource 읽어오기 수정
  backend/main-service/src/main/java/kkakka/mainservice/DataLoadRunner.java
Labels: 🍃 BE, ❗️ 이슈

#111 Chore/config-monitor 적용 및 Micrometer 적용
  backend/apigateway-service/build.gradle
  backend/config-service/build.gradle
  backend/config-service/src/main/java/org/springframework/cloud/config/monitor/PropertyPathEndpoint.java
  backend/main-service/build.gradle
Labels: 👷 인프라, 🍃 BE, main-service

#106 feat/refactor: API 문서 수정, 로깅 설정 추가, 카테고리 데이터 변경
  backend/main-service/src/docs/asciidoc/auth_member.adoc
  backend/main-service/src/docs/asciidoc/cart_order_review.adoc
  backend/main-service/src/docs/asciidoc/coupon.adoc
  backend/main-service/src/docs/asciidoc/index.adoc
  backend/main-service/src/docs/asciidoc/product.adoc
  backend/main-service/src/main/java/kkakka/mainservice/DataLoader.java
  backend/main-service/src/main/java/kkakka/mainservice/common/LogAop.java
  backend/main-service/src/main/java/kkakka/mainservice/common/config/LogConfig.java
  backend/main-service/src/main/resources/bootstrap.yml
Labels: 🛠 리팩토링, 🍃 BE

#112 fix: ProductOrder 엔티티의 'count'를 'quantity'로 수정
  backend/main-service/src/main/resources/db/migration/V2210191147_change_product_order_quantity.sql
Labels: 🍃 BE, 🚨 핫픽스

#113 feature: 주문취소 기능 구현
  backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
  backend/main-service/src/main/java/kkakka/mainservice/cart/domain/repository/CartItemRepository.java
  backend/main-service/src/main/java/kkakka/mainservice/common/exception/NotOrderOwnerException.java
  backend/main-service/src/main/java/kkakka/mainservice/member/member/ui/dto/ProductOrderResponse.java
  backend/main-service/src/main/java/kkakka/mainservice/order/application/OrderService.java
  backend/main-service/src/main/java/kkakka/mainservice/order/application/dto/MemberProductOrderDto.java
  backend/main-service/src/main/java/kkakka/mainservice/order/domain/Order.java
  backend/main-service/src/main/java/kkakka/mainservice/order/domain/ProductOrder.java
  backend/main-service/src/main/java/kkakka/mainservice/order/domain/repository/ProductOrderRepository.java
  backend/main-service/src/main/java/kkakka/mainservice/order/ui/OrderController.java
  backend/main-service/src/main/resources/db/migration/V2210191457__add_productorder_deleted.sql
Labels: 🛠 리팩토링, 🚀 기능, 🍃 BE

#117 fix: gradle 의존성 옵션 변경, restdocs 문서 설정 변경, static resource 읽도록 mvc 설정 수정
  backend/main-service/build.gradle
  backend/main-service/src/main/java/kkakka/mainservice/common/LogAop.java
  backend/main-service/src/main/java/kkakka/mainservice/common/config/WebMvcConfig.java
  backend/main-service/src/main/resources/bootstrap.yml
  backend/main-service/src/main/resources/logback-spring.xml
Labels: 📋 문서, 🍃 BE, 🚨 핫픽스

#124 Feat: 관리자 api 작업 및 작업에 따른 컴포넌트 분리, 장바구니, 결제 페이지 할인 반영, 버튼 스타일 수정
  frontend/components/admin/ApplyCategory.js
  frontend/components/admin/ApplyGrade.js
  frontend/components/admin/ApplyProduct.js
  frontend/components/admin/CouponEnrollTable.js
  frontend/components/admin/CouponSearchTable.js
  frontend/components/admin/DiscountEnrollTable.js
  frontend/components/admin/DiscountSearchTable.js
  frontend/components/admin/ProductSearch.js
  frontend/components/admin/PromotionEnroll.js
  frontend/components/admin/ValidDate.js
  frontend/components/admin/ValidDuration.js
  frontend/components/common/Button/Button.js
  frontend/components/main/Visual.js
  frontend/components/mypage/MyCoupon.js
  frontend/components/mypage/MyCouponCard.js
  frontend/components/mypage/MyOrder.js
  frontend/next.config.js
  frontend/pages/member/cart.js
  frontend/pages/payment/index.js
Labels: 🚀 기능, 🌠 FE, frontCI

#126 refactor: 쿠폰 등록완료 알림, 유튜브 음소거
  frontend/components/admin/CouponEnrollTable.js
  frontend/components/main/Youtube.js
Labels: 🛠 리팩토링, 🌠 FE, frontCI

#127 feat: 상품 상세 페이지에 영양정보, 후기 수정
  frontend/components/product/productDetail/Nutri.js
  frontend/layouts/ProductDetailLayout.js
  frontend/pages/member/cart.js
Labels: 🚀 기능, 🌠 FE, frontCI

#130 Refactor: 쿠폰 등록완료 알림, 유튜브 음소거, 상품목록 사이드바 순서, 관리자페이지 상품 목록 스크롤바
  frontend/components/admin/ApplyProduct.js
  frontend/components/admin/CouponEnrollTable.js
  frontend/components/admin/CouponSearchTable.js
  frontend/components/admin/DiscountEnrollTable.js
  frontend/components/admin/DiscountSearchTable.js
  frontend/components/admin/ProductSearch.js
  frontend/components/product/Sidebar.js
  frontend/pages/payment/index.js
Labels: 🛠 리팩토링, 🚀 기능, 🌠 FE, frontCI

#131 Refactor: 관리자 페이지 스크롤 수정
  frontend/components/admin/ApplyProduct.js
  frontend/components/admin/CouponEnrollTable.js
  frontend/components/admin/DiscountEnrollTable.js
  frontend/components/admin/PromotionEnroll.js
Labels: 🛠 리팩토링, 🌠 FE, frontCI

#133 feat: 회원 주문내역 레이아웃 수정, 더보기 구현, 후기 작성 구현
  frontend/components/mypage/MyOrderTemp.js
  frontend/components/mypage/MyProductOrder.js
  frontend/components/mypage/review/RangeWithIcons.js
  frontend/components/mypage/review/Review.js
  frontend/components/mypage/review/StartIcon.js
  frontend/components/mypage/review/useInputRating.js
  frontend/layouts/MyPageLayout.js
  frontend/pages/member/cart.js
  frontend/pages/payment/index.js
Labels: 🛠 리팩토링, 🚀 기능, 🌠 FE

#128 fix: logging 설정 원래대로 변경
  backend/main-service/src/main/resources/bootstrap.yml
  backend/main-service/src/main/resources/logback-spring.xml
Labels: 🚨 핫픽스, main-service

#134 fix: review 조회에 productId 고정값에서 실제 id로 변경
  frontend/pages/product/productDetail/index.js
Labels: 🌠 FE, 🚨 핫픽스, frontCI

#135 hotfix: 결제창 쿠폰모달 import
  frontend/pages/payment/index.js
Labels: 🚀 기능, 🌠 FE, frontCI

#136 fix: 상품 상세페이지에서 후기가 조회되지 않는 문제 해결
  frontend/components/product/productDetail/Review.js
  frontend/layouts/ProductDetailLayout.js
  frontend/pages/product/productDetail/index.js
Labels: 🌠 FE, 🚨 핫픽스, frontCI

#137 hotfix: 결제 쿠폰모달 함수명 변경
  frontend/pages/payment/index.js
Labels: 🌠 FE, 🚨 핫픽스, frontCI

#139 feat: 상품 상세정보, 후기에 평점 추가
  frontend/components/mypage/review/RangeWithIcons.js
  frontend/components/mypage/review/Review.js
  frontend/components/mypage/review/StartIcon.js
  frontend/components/product/productDetail/Review.js
  frontend/layouts/ProductDetailLayout.js
Labels: 🚀 기능, 🌠 FE, frontCI

#151 feat: auth-service 에러핸들링
  backend/auth-service/src/main/java/kkakka/authservice/auth/application/SocialAuthenticateException.java
  backend/auth-service/src/main/java/kkakka/authservice/auth/application/SocialClient.java
  backend/auth-service/src/main/java/kkakka/authservice/auth/infrastructure/LogAop.java
  backend/auth-service/src/main/java/kkakka/authservice/auth/infrastructure/google/GoogleClient.java
  backend/auth-service/src/main/java/kkakka/authservice/auth/infrastructure/kakao/KakaoClient.java
  backend/auth-service/src/main/java/kkakka/authservice/auth/infrastructure/naver/NaverClient.java
  backend/auth-service/src/main/java/kkakka/authservice/auth/ui/AuthController.java
  backend/auth-service/src/main/resources/application.yml
  backend/auth-service/src/main/resources/bootstrap.yml
  backend/auth-service/src/main/resources/logback-spring.xml
  backend/main-service/src/main/java/kkakka/mainservice/common/exception/InvalidSocialAccountException.java
  backend/main-service/src/main/java/kkakka/mainservice/common/exception/SocialServiceException.java
  backend/main-service/src/main/java/kkakka/mainservice/member/auth/application/AuthClient.java
  backend/main-service/src/main/java/kkakka/mainservice/member/auth/infrastructure/AuthErrorDecoder.java
  backend/main-service/src/main/java/kkakka/mainservice/member/auth/infrastructure/FeignConfig.java
  backend/main-service/src/test/java/kkakka/mainservice/AcceptanceTest.java
  backend/main-service/src/test/java/kkakka/mainservice/member/acceptance/LoginAcceptanceTest.java
  backend/main-service/src/test/java/kkakka/mainservice/review/acceptance/ReviewAcceptanceTest.java
Labels: 🚀 기능, 🍃 BE

#165 refactor: auth feignclient 로깅 추가
  backend/main-service/src/main/java/kkakka/mainservice/member/auth/application/AuthClient.java
  backend/main-service/src/main/java/kkakka/mainservice/member/auth/infrastructure/FeignLogger.java
  backend/main-service/src/main/resources/bootstrap.yml
Labels: 🛠 리팩토링, 🍃 BE
